### ISSUE TITLE
Can't make~

### ISSUE THREAD

**Issue by smarttang** [HISONA/https_client#1]
Compiling: main.c ....
gcc -c -fPIC -DHAVE_CONFIG_H -D_U_="__attribute__((unused))" -O2 -I../mbedtls-2.2.1/include -o main.o main.c
Compiling: https.c ....
gcc -c -fPIC -DHAVE_CONFIG_H -D_U_="__attribute__((unused))" -O2 -I../mbedtls-2.2.1/include -o https.o https.c
https.c:14:25: 错误：mbedtls/net.h：没有那个文件或目录
https.c:15:29: 错误：mbedtls/entropy.h：没有那个文件或目录
https.c:16:30: 错误：mbedtls/ctr_drbg.h：没有那个文件或目录
https.c:17:27: 错误：mbedtls/error.h：没有那个文件或目录
https.c:18:27: 错误：mbedtls/certs.h：没有那个文件或目录
https.c:47: 错误：expected specifier-qualifier-list before ‘mbedtls_net_context’
https.c: 在函数‘https_init’中:
https.c:461: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:462: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:463: 错误：‘HTTP_INFO’没有名为‘cacert’的成员
https.c:464: 错误：‘HTTP_INFO’没有名为‘ctr_drbg’的成员
https.c:467: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c: 在函数‘https_close’中:
https.c:481: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:484: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:488: 错误：‘HTTP_INFO’没有名为‘cacert’的成员
https.c:489: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:490: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:491: 错误：‘HTTP_INFO’没有名为‘ctr_drbg’的成员
https.c:492: 错误：‘HTTP_INFO’没有名为‘entropy’的成员
https.c: 在文件层：
https.c:504: 错误：expected ‘)’ before ‘*’ token
https.c: 在函数‘https_connect’中:
https.c:620: 错误：‘HTTP_INFO’没有名为‘entropy’的成员
https.c:622: 错误：‘HTTP_INFO’没有名为‘ctr_drbg’的成员
https.c:622: 错误：‘mbedtls_entropy_func’未声明(在此函数内第一次使用)
https.c:622: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
https.c:622: 错误：所在的函数内也只报告一次。)
https.c:622: 错误：‘HTTP_INFO’没有名为‘entropy’的成员
https.c:628: 错误：‘HTTP_INFO’没有名为‘cacert’的成员
https.c:628: 错误：‘mbedtls_test_cas_pem’未声明(在此函数内第一次使用)
https.c:629: 错误：‘mbedtls_test_cas_pem_len’未声明(在此函数内第一次使用)
https.c:635: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:636: 错误：‘MBEDTLS_SSL_IS_CLIENT’未声明(在此函数内第一次使用)
https.c:637: 错误：‘MBEDTLS_SSL_TRANSPORT_STREAM’未声明(在此函数内第一次使用)
https.c:638: 错误：‘MBEDTLS_SSL_PRESET_DEFAULT’未声明(在此函数内第一次使用)
https.c:646: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:646: 错误：‘MBEDTLS_SSL_VERIFY_OPTIONAL’未声明(在此函数内第一次使用)
https.c:647: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:647: 错误：‘HTTP_INFO’没有名为‘cacert’的成员
https.c:648: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:648: 错误：‘mbedtls_ctr_drbg_random’未声明(在此函数内第一次使用)
https.c:648: 错误：‘HTTP_INFO’没有名为‘ctr_drbg’的成员
https.c:649: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:651: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:651: 错误：‘HTTP_INFO’没有名为‘conf’的成员
https.c:657: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:664: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:664: 错误：‘MBEDTLS_NET_PROTO_TCP’未声明(在此函数内第一次使用)
https.c:672: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:672: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:672: 错误：‘mbedtls_net_send’未声明(在此函数内第一次使用)
https.c:672: 错误：‘mbedtls_net_recv’未声明(在此函数内第一次使用)
https.c:672: 错误：‘mbedtls_net_recv_timeout’未声明(在此函数内第一次使用)
https.c:674: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:676: 错误：‘MBEDTLS_ERR_SSL_WANT_READ’未声明(在此函数内第一次使用)
https.c:676: 错误：‘MBEDTLS_ERR_SSL_WANT_WRITE’未声明(在此函数内第一次使用)
https.c: 在函数‘https_write’中:
https.c:694: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:696: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:698: 错误：‘MBEDTLS_ERR_SSL_WANT_WRITE’未声明(在此函数内第一次使用)
https.c: 在函数‘https_read’中:
https.c:714: 错误：‘HTTP_INFO’没有名为‘ssl’的成员
https.c:718: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c: 在函数‘http_get’中:
https.c:759: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:777: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:834: 错误：‘MBEDTLS_ERR_SSL_WANT_READ’未声明(在此函数内第一次使用)
https.c: 在函数‘http_post’中:
https.c:898: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:901: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:918: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:982: 错误：‘MBEDTLS_ERR_SSL_WANT_READ’未声明(在此函数内第一次使用)
https.c: 在函数‘http_open_chunked’中:
https.c:1052: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:1055: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c:1071: 错误：‘HTTP_INFO’没有名为‘ssl_fd’的成员
https.c: 在函数‘http_read_chunked’中:
https.c:1195: 错误：‘MBEDTLS_ERR_SSL_WANT_READ’未声明(在此函数内第一次使用)
make: *** [https.o] 错误 1

**Comment by HISONA** [comment]
You must build and include  the mbedtls library(https://tls.mbed.org/).  

1. download mbedtls-2.4.2-apache.tgz from mbedlts site(https://tls.mbed.org/).
2. in mbedtls-2.4.2 directory, make the library. 
    > make
3. Modified the "Makefile" in https_client with the mbedtls include and library path.
4. make 

Good Luck.

**Comment by smarttang** [comment]
thx, I try test~。。

**Comment by drozdzamadeusz** [comment]
Have you found a solution to this problem? I have exactly the same issue. Please help I trying to compile my program whole day, nothing works for me.

**Comment by smarttang** [comment]
> Have you found a solution to this problem? I have exactly the same issue. Please help I trying to compile my program whole day, nothing works for me.

no,  i give up.
